- name: nRF52840-nicenano
  bootloaderURL: https://github.com/adafruit/Adafruit_nRF52_Bootloader/releases/download/0.9.2/update-nice_nano_bootloader-0.9.2_nosd.uf2
  fulleraseURL: https://flasher.meshtastic.org/uf2/nrf_erase2.uf2
  firmwareURL: http://mrekin.duckdns.org/flasher//api/firmware?t=nrf52_promicro_diy_tcxo&u=1&e=false

- name: RPI-RP2
  fulleraseURL: https://flasher.meshtastic.org/uf2/pico_erase.uf2